/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 * ---------------------------------------------------------------------------
 * S-h-e-n-e-n-d-e-h-o-w-a--H-i-g-h--S-c-h-o-o-l--T-e-c-h-n-o-l-o-g-y--D-e-p-t
 * ----------------------------------------------------------------------------
 * FILE: Expression file is undefined on line 14, column 12 in Templates/GUIForms/JFrame.java. .java
 *
 * DATE: Nov 30, 2016
 *
 * PURPOSE: Frame
 *
 * @author mr Hanley
 * @version 1.0
 * ----------------------------------------------------------------------------
 *
 * h-a-n-l-e-y.c-o-.-n-r------t-e-a-m-2-0-.-c-o-m----------------------------
 */
public class ShenHauntedFrame extends javax.swing.JFrame {

    /** Creates new form ShenHauntedFrame */
    public ShenHauntedFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTP = new javax.swing.JTabbedPane();
        aboutTAB = new javax.swing.JPanel();
        house1TAB = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        mainTP.setFont(new java.awt.Font("Chiller", 1, 14)); // NOI18N

        aboutTAB.setFont(new java.awt.Font("Chiller", 1, 14)); // NOI18N

        javax.swing.GroupLayout aboutTABLayout = new javax.swing.GroupLayout(aboutTAB);
        aboutTAB.setLayout(aboutTABLayout);
        aboutTABLayout.setHorizontalGroup(
            aboutTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        aboutTABLayout.setVerticalGroup(
            aboutTABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        mainTP.addTab("About", null, aboutTAB, "");

        house1TAB.setFont(new java.awt.Font("Chiller", 1, 14)); // NOI18N

        javax.swing.GroupLayout house1TABLayout = new javax.swing.GroupLayout(house1TAB);
        house1TAB.setLayout(house1TABLayout);
        house1TABLayout.setHorizontalGroup(
            house1TABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 635, Short.MAX_VALUE)
        );
        house1TABLayout.setVerticalGroup(
            house1TABLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
        );

        mainTP.addTab("House 1", null, house1TAB, "");

        getContentPane().add(mainTP);
        mainTP.setBounds(10, 10, 640, 490);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShenHauntedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShenHauntedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShenHauntedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShenHauntedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShenHauntedFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel aboutTAB;
    private javax.swing.JPanel house1TAB;
    private javax.swing.JTabbedPane mainTP;
    // End of variables declaration//GEN-END:variables

}
